### ISSUE TITLE
 window is not defined render server side

### ISSUE THREAD

**Issue by canotech** [jodit/jodit-react#14]
Hi I implementing you library with react and nextjs, and when I reload the page, I get the error: 

window is not defined
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/albertocano/Documents/projects/project/project/node_modules/jodit/build/jodit.min.js:9:224)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.jodit (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:581:18)
    at __webpack_require__ (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
    at Module../pages/test2.jsx (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:421:63)
    at __webpack_require__ (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
    at Object.4 (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:503:18)
    at __webpack_require__ (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
    at /Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:91:18
    at Object.<anonymous> (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:94:10)

It's obviously that window obejct is only defined on browser side, but do you can support render server side? please

**Comment by mahip-nickelfox** [comment]
Same issue.
Is there any work around found to fix this?

**Comment by Gladiolys** [comment]
For next js you can use this:
```
import React from 'react';
import dynamic from 'next/dynamic';

const importJodit = () => import('jodit-react');

const JoditEditor = dynamic(importJodit, {
    ssr: false,
});
```

**Comment by Gladiolys** [comment]
> **Hi I implementing you library with react and nextjs, and when I reload the page, I get the error:**
> 
> window is not defined
> ReferenceError: window is not defined
> at Object. (/Users/albertocano/Documents/projects/project/project/node_modules/jodit/build/jodit.min.js:9:224)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object.jodit (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:581:18)
> at **webpack_require** (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
> at Module../pages/test2.jsx (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:421:63)
> at **webpack_require** (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
> at Object.4 (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:503:18)
> at **webpack_require** (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:23:31)
> at /Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:91:18
> at Object. (/Users/albertocano/Documents/projects/project/project/.next/server/static/development/pages/test2.js:94:10)
> 
> **It's obviously that window obejct is only defined on browser side, but do you can support render server side? please**

For next js you can use this:
```
import React from 'react';
import dynamic from 'next/dynamic';

const importJodit = () => import('jodit-react');

const JoditEditor = dynamic(importJodit, {
    ssr: false,
});
```

**Comment by Fedeorlandau** [comment]
For Gatsby:

```
import React from "react";

const Jodit = React.lazy(() => {
  return import("jodit-react");
});

export const RichTextEditor = (props) => {
  const { value, onChange, ...otherProps } = props;
  const isSSR = typeof window === "undefined";

  return (
    <>
      {!isSSR && (
        <React.Suspense fallback={<div>Loading RTE</div>}>
          <Jodit value={value} onChange={onChange} {...otherProps}/>
        </React.Suspense>
      )}
    </>
  );
});
```

**Comment by oqnunes** [comment]
> For Gatsby:
> 
> ```
> import React, { useState } from "react";
> 
> const Jodit = React.lazy(() => {
>   return import("jodit-react");
> });
> 
> export const RichTextEditor = () => {
>   const [value, setValue] = useState("");
>   const isSSR = typeof window === "undefined";
> 
>   return (
>     <>
>       {!isSSR && (
>         <React.Suspense fallback={<div>Loading RTE</div>}>
>           <Jodit value={value} onChange={(val) => setValue(val)}/>
>         </React.Suspense>
>       )}
>     </>
>   );
> });
> ```

That solution worked for me @Fedeorlandau, you definitely have a place in heaven!

`"gatsby": "^2.18.12"`

**Comment by Fedeorlandau** [comment]
> > For Gatsby:
> > ```
> > import React, { useState } from "react";
> > 
> > const Jodit = React.lazy(() => {
> >   return import("jodit-react");
> > });
> > 
> > export const RichTextEditor = () => {
> >   const [value, setValue] = useState("");
> >   const isSSR = typeof window === "undefined";
> > 
> >   return (
> >     <>
> >       {!isSSR && (
> >         <React.Suspense fallback={<div>Loading RTE</div>}>
> >           <Jodit value={value} onChange={(val) => setValue(val)}/>
> >         </React.Suspense>
> >       )}
> >     </>
> >   );
> > });
> > ```
> 
> That solution worked for me @Fedeorlandau, you definitely have a place in heaven!
> 
> `"gatsby": "^2.18.12"`

Thank you @oqnunes. I strongly recommend you checking out https://github.com/ianstormtaylor/slate and https://docs.slatejs.org/ before focusing on jodit. I've found an enormous amount of bugs on jodit while working with react and SSR. Some stuff like dynamic configuration for the rte or customize some inputs on the controls aren't 100% possible with jodit. Regards!
