### ISSUE TITLE
Warning: React does not recognize the `formState` / `fieldState` prop on a DOM element.

### ISSUE THREAD

**Issue by leandertolksdorf** [jodit/jodit-react#148]
I want to integrate the JoditEditor with react-hook-forms like this:
```
import React from "react"
import Layout from "../components/Layout"
import { useForm, Controller } from "react-hook-form"
import { Button, Form } from "react-bootstrap"
import JoditEditor from "jodit-react"

function TextEdit({ create, slug }) {
  const { control, handleSubmit } = useForm()

  const onSubmit = (data) => console.log(data)

  const joditConfig = {
    readonly: false
  }

  return (
    <Layout title={create ? "Create new Text" : "Edit text"}>
      <Form onSubmit={handleSubmit(onSubmit)}>
        <Controller
          name="content"
          control={control}
          defaultValue={""}
          render={({ field }) => (
            <JoditEditor
              config={joditConfig}
              value={field.value}
              onChange={field.onChange}
              onBlur={field.onBlur}
              ref={field.ref}
            />
          )}
        />
        <Button type="submit">Submit</Button>
      </Form>
    </Layout>
  )
}

export default TextEdit
```

I'm getting these two warnings in the console:
```
Warning: React does not recognize the `formState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `formstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at http://localhost:3000/static/js/vendors~main.chunk.js:41634:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:41716:3
    at Controller (http://localhost:3000/static/js/vendors~main.chunk.js:75236:35)
    at form
    at http://localhost:3000/static/js/vendors~main.chunk.js:41371:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:40230:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:44350:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:40415:3
    at Layout (http://localhost:3000/static/js/main.chunk.js:310:3)
    at TextEdit (http://localhost:3000/static/js/main.chunk.js:1499:3)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:88593:3)
    at Router
    at App

index.js:1 Warning: React does not recognize the `fieldState` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fieldstate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at input
    at http://localhost:3000/static/js/vendors~main.chunk.js:41634:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:41716:3
    at Controller (http://localhost:3000/static/js/vendors~main.chunk.js:75236:35)
    at form
    at http://localhost:3000/static/js/vendors~main.chunk.js:41371:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:40230:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:44350:3
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:40415:3
    at Layout (http://localhost:3000/static/js/main.chunk.js:310:3)
    at TextEdit (http://localhost:3000/static/js/main.chunk.js:1499:3)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:88593:3)
    at Router
    at App
```

I'm only getting this error on the JoditEditor, other fields work without a warning.

**Comment by obsd** [comment]
I get the same errors

**Comment by tc-root-user** [comment]
Same

**Comment by abdul3Edge** [comment]
how to resolve this issue . !!

**Comment by Joacofb** [comment]
It helps for me!

https://reactjs.org/warnings/unknown-prop.html

**Comment by quocbinh-npm9081** [comment]
this is my issue  :(( help me ples

**Comment by RobyCigar** [comment]
same here, any solution?
heres my code using material ui
```
        <ListItem>
          <Controller
            control={control}
            name="name"
            render={(field) => (
              <TextField
                {...field}
                className="w-full"
                label="Nama"
                placeholder="Masukkan Nama"
                helperText="Wajib diisi"
                value={state.name}
                onChange={(e) => setState({ ...state, name: e.target.value })}
              />
            )}
          />
        </ListItem>
```

**Comment by nikkaknik** [comment]
> same here, any solution? heres my code using material ui
> 
> ```
>         <ListItem>
>           <Controller
>             control={control}
>             name="name"
>             render={(field) => (
>               <TextField
>                 {...field}
>                 className="w-full"
>                 label="Nama"
>                 placeholder="Masukkan Nama"
>                 helperText="Wajib diisi"
>                 value={state.name}
>                 onChange={(e) => setState({ ...state, name: e.target.value })}
>               />
>             )}
>           />
>         </ListItem>
> ```

`render={( { field } ) => (`

**Comment by JovanJevtic** [comment]
I had same problem with @shadcn/ui. Solution was typing it like:
`render={ ({ field }) => (
 <FormItem>
                          ...
 </FormItem>
)}` 
and not like:
`render={(field) => {}} `

**Comment by thefool76** [comment]
facing the same issue with @shadcn/ui while using form component :(

**Comment by JovanJevtic** [comment]
> facing the same issue with @shadcn/ui while using form component :(

https://github.com/jodit/jodit-react/issues/148#issuecomment-1790802625

**Comment by thefool76** [comment]
Thank you @JovanJevtic for pointing out the solution I was so busy that I forgot the check it.

**Comment by M0Leo** [comment]
NVM The problem was the `{...form}` in the box component

**Comment by viral-siddhapura** [comment]
> Thank you @JovanJevtic for pointing out the solution I was so busy that I forgot to check it.

in my case it is not working, I did a similar thing I guess. See below code: 

```
<div className="mt-10">
                <Form {...form}>
                    <form
                        onSubmit={form.handleSubmit(onSubmit)}
                    >
                        <div className="grid grid-cols-2 gap-10 mb-5">
                            <FormField
                                control={form.control}
                                name="firstName"
                                render={ ({field}) => (
                                    <FormItem>
                                        <FormLabel>First Name:</FormLabel>
                                        <FormControl>
                                            <Input
                                                {...field}
                                                placeholder="Enter first name"
                                                type="text"
                                            />
                                        </FormControl>
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="lastName"
                                render={(field) => (
                                    <FormItem>
                                        <FormLabel>Last Name</FormLabel>
                                        <FormControl>
                                            <Input
                                                {...field}
                                                placeholder="Enter last name"
                                                type="text"
                                            />
                                        </FormControl>
                                    </FormItem>
                                )}
                            />
                        </div>
                        <FormField
                            control={form.control}
                            name="email"
                            render={(field) => (
                                <FormItem className="mb-5">
                                    <FormLabel>Email Address</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder="Enter your email"
                                            type="email"
                                        />
                                    </FormControl>
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="location"
                            render={(field) => (
                                <FormItem>
                                    <FormLabel>Location</FormLabel>
                                    <FormControl>
                                        <Input
                                            {...field}
                                            placeholder="Enter your location"
                                            type="text"
                                        />
                                    </FormControl>
                                </FormItem>
                            )}
                        />
                        <Button
                            className="mt-5 w-full"
                            type="submit"
                        >Continue</Button>
                    </form>
                </Form>
            </div>
```
