### ISSUE TITLE
onDelete error when select and delete an image

### ISSUE THREAD

**Issue by d4n4mp** [jodit/jodit-react#226]
When I select and press delete or backspace on keyboard, the app brokeand show:

Compiled with problems:
×
ERROR
Node element must be in editor
TypeError: Node element must be in editor
    at t.error (http://localhost:3000/static/js/bundle.js:315794:20)
    at e.select (http://localhost:3000/static/js/bundle.js:317071:50)
    at t.onDelete (http://localhost:3000/static/js/bundle.js:328430:78)
    at HTMLDivElement.<anonymous> (http://localhost:3000/static/js/bundle.js:328387:109)
    at HTMLDivElement.y (http://localhost:3000/static/js/bundle.js:314217:85)

Any suggest?

**Comment by kerocode** [comment]
same here i am receiving this error on delete using keyboard delete button.

**Comment by xdan** [comment]
Reproduced your exact scenario on the current editor — select an image, hit Delete or Backspace — and it removes the image cleanly, no 'Node element must be in editor' error. This got fixed in the core somewhere after the version you were on; I've added regression tests for both keys so it stays fixed. Update jodit-react to the latest and you're good. Closing.
